### PR TITLE
Fix secret template

### PR DESCRIPTION
**Pull request by bumarcell**

### CODE REVIEW

**Review by galexrt — APPROVED** [review]

**Comment by galexrt** [comment]
Thanks!

**Comment by StopMotionCuber** [comment]
This is referencing `Values.config.rgw.multiMode.enabled`. However, in the README.md multiMode is placed at `Values.config.multiMode.enabled`, missing the `rgw` key in the middle. Therefore this chart fails to deploy with default settings. Would be great if this could be fixed at either place

**Comment by bumarcell** [comment]
@StopMotionCuber You are right. There’s an error in the default values, which makes it’s way to the auto-generated documentation.

**Comment by galexrt** [comment]
@StopMotionCuber @bumarcell I have pushed a commit which should hopefully address both issues (chart version will be `1.5.0`):

* Switched `config.rgw.multiMode` to `config.multiMode`
* Fix `config.multiMode.enabled` not being able to be a boolean.

Please let me know if that fixes the mentioned issues. :smiley:

**Comment by bumarcell** [comment]
@galexrt I would actually keep `multiMode` inside `rgw` 😄 it makes sense to me at least.
Another thing that caused me a problem was `env` template in the _deployment_; I had to set `.Values.config.rgw.existingSecret.name=nil` although I'm not using an existing secret for one rgw but rather a realms.yaml file for multiple ones.

**Comment by StopMotionCuber** [comment]
This works for me with default settings, thanks for the quick fix

**Pull request merged**
